export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const DONE_APPOINTMENT = 'DONE_APPOINTMENT';
export const GET_APPOINTMENT_BATCH = 'GET_APPOINTMENT_BATCH';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
