export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const COMPLETE_PROFILE = 'COMPLETE_PROFILE';
export const FETCH_PROFILE = 'FETCH_PROFILE';

export const APPLY_FOR_ORG = 'APPLY_FOR_ORG';
export const APPLY_FOR_ORG_FAIL = 'APPLY_FOR_ORG_FAIL';

export const GET_BOOKED_SERVICES = 'GET_BOOKED_SERVICES';
export const BOOK_VACCINE = 'BOOK_VACCINE';
export const CANCEL_VACCINE_BOOKING = 'CANCEL_VACCINE_BOOKING';

export const GET_ALL_VACCINES = 'GET_ALL_VACCINES';
export const GET_ALL_VACCINES_FAIL = 'GET_ALL_VACCINES_FAIL';

export const GET_EMERGENCY_SERVICES = 'GET_EMERGENCY_SERVICES';

export const GET_BLOOD_SERVICES = 'GET_BLOOD_SERVICES';

export const FETCH_DOCTORS = 'FETCH_DOCTORS';
export const BOOK_APPOINTMENT = 'BOOK_APPOINTMENT';
export const GET_AVAILABLE_APPOINTMENTS = 'GET_AVAILABLE_APPOINTMENTS';
export const CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT';
