export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const COMPLETE_PROFILE = 'COMPLETE_PROFILE';
export const FETCH_PROFILE = 'FETCH_PROFILE';

export const APPLY_FOR_ORG = 'APPLY_FOR_ORG';
export const APPLY_FOR_ORG_FAIL = 'APPLY_FOR_ORG_FAIL';

export const GET_BOOKED_VACCINES = 'GET_BOOKED_VACCINES';
export const BOOK_VACCINE = 'BOOK_VACCINE';
export const CANCEL_VACCINE_BOOKING = 'CANCEL_VACCINE_BOOKING';

export const GET_ALL_VACCINES = 'GET_ALL_VACCINES';
export const GET_ALL_VACCINES_FAIL = 'GET_ALL_VACCINES_FAIL';
