export const FETCH_ORG_APPLICATIONS_SUCCESS = 'FETCH_ORG_APPLICATIONS_SUCCESS';
export const FETCH_ORG_APPLICATIONS_FAIL = 'FETCH_ORG_APPLICATIONS_FAIL';

export const APPROVE_APPLICATION_SUCCESS = 'APPROVE_APPLICATION_SUCCESS';
export const APPROVE_APPLICATION_FAIL = 'APPROVE_APPLICATION_FAIL';
