export const ADD_VACCINE = 'ADD_VACCINE';
export const GET_ALL_VACCINES = 'GET_ALL_VACCINES';
export const DEL_ALL_VACCINES = 'DEL_ALL_VACCINES';
export const GET_VACCINE_BY_BATCH = 'GET_VACCINE_BY_BATCH';
export const GET_VACCINE_BY_BATCH_FAIL = 'GET_VACCINE_BY_BATCH_FAIL';
export const DEL_VACCINE_FROM_BATCH = 'DEL_VACCINE_FROM_BATCH';
export const FILTER_VACCINE_BATCH = 'FILTER_VACCINE_BATCH';
