export const GET_ALL_VACCINES = 'GET_ALL_VACCINES';
export const DEL_ALL_VACCINES = 'DEL_ALL_VACCINES';
export const GET_VACCINE_BY_BATCH = 'GET_VACCINE_BY_BATCH';
export const GET_VACCINE_BY_BATCH_FAIL = 'GET_VACCINE_BY_BATCH_FAIL';
export const DEL_VACCINE_FROM_BATCH = 'DEL_VACCINE_FROM_BATCH';
export const FILTER_VACCINE_BATCH = 'FILTER_VACCINE_BATCH';
export const SET_DONE_UNDONE_VACCINE = 'SET_DONE_UNDONE_VACCINE';

export const ORG_ADD_EMERGENCY = 'ORG_ADD_EMERGENCY';
export const ORG_EDIT_EMERGENCY = 'ORG_EDIT_EMERGENCY';
export const ORG_DELETE_EMERGENCY_SERVICE = 'ORG_DELETE_EMERGENCY_SERVICE';
export const ORG_GET_EMERGENCY_SERVICES = 'ORG_GET_EMERGENCY_SERVICES';

export const ORG_ADD_BLOOD = 'ORG_ADD_BLOOD';
export const ORG_EDIT_BLOOD = 'ORG_EDIT_BLOOD';
export const ORG_DELETE_BLOOD = 'ORG_DELETE_BLOOD';
export const ORG_GET_BLOOD_PROVIDE_SERVICES = 'ORG_GET_BLOOD_PROVIDE_SERVICES';

export const ORG_GET_OXYGEN_SERVICES = 'ORG_GET_OXYGEN_SERVICES';
export const ORG_DELETE_OXYGEN_SERVICES = 'ORG_DELETE_OXYGEN_SERVICES';
export const ORG_GET_OXYGEN_BATCH = 'ORG_GET_OXYGEN_BATCH';
export const SET_DONE_UNDONE_OXYGEN = 'SET_DONE_UNDONE_OXYGEN';
export const ORG_DELETE_OXYGEN_BY_ID = 'ORG_DELETE_OXYGEN_BY_ID';

export const ORG_GET_BEDS_SERVICES = 'ORG_GET_BEDS_SERVICES';
export const ORG_DELETE_BED_SERVICES = 'ORG_DELETE_BED_SERVICES';

export const ORG_GET_BLOOD_TEST_SERVICES = 'ORG_GET_BLOOD_TEST_SERVICES';
export const ORG_GET_BLOOD_TEST_BATCH = 'ORG_GET_BLOOD_TEST_BATCH';
export const ORG_DELETE_BLOOD_TEST_SERVICES = 'ORG_DELETE_BLOOD_TEST_SERVICES';
export const ORG_DELETE_BLOOD_TEST_BY_ID = 'ORG_DELETE_BLOOD_TEST_BY_ID';
