export const ADD_VACCINE = 'ADD_VACCINE';
export const GET_ALL_VACCINES = 'GET_ALL_VACCINES';
export const DEL_ALL_VACCINES = 'DEL_ALL_VACCINES';
export const GET_VACCINE_BY_BATCH = 'GET_VACCINE_BY_BATCH';
export const GET_VACCINE_BY_BATCH_FAIL = 'GET_VACCINE_BY_BATCH_FAIL';
export const DEL_VACCINE_FROM_BATCH = 'DEL_VACCINE_FROM_BATCH';
export const FILTER_VACCINE_BATCH = 'FILTER_VACCINE_BATCH';

export const ORG_ADD_EMERGENCY = 'ORG_ADD_EMERGENCY';
export const ORG_EDIT_EMERGENCY = 'ORG_EDIT_EMERGENCY';
export const ORG_DELETE_EMERGENCY_SERVICE = 'ORG_DELETE_EMERGENCY_SERVICE';
export const ORG_GET_EMERGENCY_SERVICES = 'ORG_GET_EMERGENCY_SERVICES';
